<HEAD>
<TITLE>Tools.ProcessForm Method</TITLE>
</HEAD>

<BODY BGCOLOR=<%%= Request.Form("color") %%>>

<H1>This page is generated by the Tools component</H1>

Generated <%%= now %%><BR>

Page served <%= now %>

</BODY>