<MAP NAME="navBarOB">
<AREA SHAPE="rect" COORDS="0,0,84,34" HREF="http://www.microsoft.com/sitebuilder/">
<AREA SHAPE="rect" COORDS="88,3,140,26" HREF="http://www.microsoft.com/sitebuilder/magazine/default.asp">
<AREA SHAPE="rect" COORDS="150,3,210,26" HREF="http://www.microsoft.com/sbnmember/default.asp">
<AREA SHAPE="rect" COORDS="223,3,277,26" HREF="http://www.microsoft.com/workshop/default.asp">
<AREA SHAPE="rect" COORDS="288,3,372,26" HREF="http://www.microsoft.com/gallery/default.asp">
<AREA SHAPE="rect" COORDS="384,3,430,26" HREF="http://www.microsoft.com/devtraining/default.asp">
<AREA SHAPE="rect" COORDS="440,3,488,26" HREF="http://www.microsoft.com/sitebuilder/siteinfo/default.asp">
</MAP>

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" BGCOLOR="#003399" WIDTH="100%">
<TR>
<TD><IMG BORDER="0" WIDTH="488" HEIGHT="34" SRC="../graphics/navbar-ob.gif" USEMAP="#navBarOB" /></TD>
</TR>
</TABLE>