
<TABLE ID="tblNavBar" BORDER="0" CELLPADDING="0" CELLSPACING="0">
<TR VALIGN="top">
	<TD CLASS="clsSBNLogo" TITLE="SBN Home" HEIGHT="34" WIDTH="90"><A HREF="http://www.microsoft.com/sitebuilder/" TARGET="_top" expNoTOC="true"><IMG HEIGHT="34" WIDTH="90" BORDER="0" 
		SRC="shared/graphics/sbnlogo.gif" ALT="SBN Home" /></A></TD>
	<TD CLASS="clsNavBarItem" expItemNum="1">Magazine<BR><IMG HEIGHT="4" WIDTH="7" BORDER="0" SRC="shared/graphics/arrow.gif"></TD>
	<TD>&nbsp;|&nbsp;</TD>
	<TD CLASS="clsNavBarItem" expItemNum="2">Community<BR><IMG HEIGHT="4" WIDTH="7" BORDER="0" SRC="shared/graphics/arrow.gif"></TD>
	<TD>&nbsp;|&nbsp;</TD>
	<TD CLASS="clsNavBarItem" expItemNum="3">Workshop<BR><IMG HEIGHT="4" WIDTH="7" BORDER="0" SRC="shared/graphics/arrow.gif"></TD>
	<TD>&nbsp;|&nbsp;</TD>
	<TD CLASS="clsNavBarItem" expItemNum="4">Tools&nbsp;&amp;&nbsp;Samples<BR><IMG HEIGHT="4" WIDTH="7" BORDER="0" SRC="shared/graphics/arrow.gif"></TD>
	<TD>&nbsp;|&nbsp;</TD>
	<TD CLASS="clsNavBarItem" expItemNum="5">Training<BR><IMG HEIGHT="4" WIDTH="7" BORDER="0" SRC="shared/graphics/arrow.gif"></TD>
	<TD>&nbsp;|&nbsp;</TD>
	<TD CLASS="clsNavBarItem" expItemNum="6">Site&nbsp;Info<BR><IMG HEIGHT="4" WIDTH="7" BORDER="0" SRC="shared/graphics/arrow.gif"></TD>
	<TD WIDTH="100%"></TD>
</TR>
</TABLE>
