
	<DIV ID="divMenu1" CLASS="clsMenu" ONMOUSEOVER="Menu_hover();" ONMOUSEOUT="Menu_hover();" ONCLICK="Menu_click();">
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/default.asp">Magazine Home</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/jane.asp">Ask Jane</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/dude.asp">DHTML Dude</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/xml.asp">Extreme XML</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/starters.asp">For Starters</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/hess.asp">More or Hess</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/server.asp">Servin' It Up</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/site.asp">Site Lights</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/magazine/webmen.asp">Web Men Talking</DIV>
	</DIV>
	<DIV ID="divMenu2" CLASS="clsMenu" ONMOUSEOVER="Menu_hover();" ONMOUSEOUT="Menu_hover();" ONCLICK="Menu_click();">
		<DIV expURL="http://www.microsoft.com/sbnmember/default.asp">Member Community Home</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/freebies/default.asp">Benefits: Freebies &amp; Discounts</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/promote/default.asp">Benefits: Promote Your Site</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/connect/default.asp">Benefits: Connect with Your Peers</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/glance-lev.asp">Benefits at a Glance</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/osig/default.asp">Online Special-Interest Groups</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/levels/member.asp">Your Membership</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/freebies/stores.asp">SBN Stores</DIV>
		<DIV expURL="http://www.microsoft.com/sbnmember/apply/registration.asp">Join Now</DIV>
	</DIV>
	<DIV ID="divMenu3" CLASS="clsMenu" ONMOUSEOVER="Menu_hover();" ONMOUSEOUT="Menu_hover();" ONCLICK="Menu_click();">
		<DIV expURL="http://www.microsoft.com/workshop/default.asp">Workshop Home</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/essentials/default.asp">Essentials</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/components/default.asp">Component Development</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/delivery/default.asp">Content &amp; Component Delivery</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/database/default.asp">Data Access &amp; Databases</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/design/default.asp">Design</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/author/default.asp">DHTML, HTML &amp; CSS</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/languages/default.asp">Languages &amp; Development Tools</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/messaging/default.asp">Messaging &amp; Collaboration</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/networking/default.asp">Networking, Protocols &amp; Data Formats</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/browser/default.asp">Reusing Browser Technology</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/security/default.asp">Security &amp; Cryptography</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/server/default.asp">Server Technologies</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/imedia/default.asp">Streaming &amp; Interactive Media</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/workshop/management/default.asp">Web Content Management</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/xml/default.asp">XML (Extensible Markup Language)</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/index/">Workshop Index</DIV>
	</DIV>
	<DIV ID="divMenu4" CLASS="clsMenu" ONMOUSEOVER="Menu_hover();" ONMOUSEOUT="Menu_hover();" ONCLICK="Menu_click();">
		<DIV expURL="http://www.microsoft.com/gallery/default.asp">Tools &amp; Samples Home</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/gallery/tools/default.asp">Tools</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/gallery/samples/default.asp">Samples, Headers, Libs</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/gallery/images/default.asp">Images</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/gallery/sounds/default.asp">Sounds</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/gallery/stylesheets/default.asp">Style Sheets</DIV>
		<DIV expURL="http://www.microsoft.com/typography/fontpack/win.htm">Web Fonts</DIV>
	</DIV>
	<DIV ID="divMenu5" CLASS="clsMenu" ONMOUSEOVER="Menu_hover();" ONMOUSEOUT="Menu_hover();" ONCLICK="Menu_click();">
		<DIV expURL="http://www.microsoft.com/devtraining/default.asp">Training Home</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/seminars/default.asp">SBN Live Seminars</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/chat/default.asp">SBN Live Chats</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/roadmap/default.asp">Training Road Maps</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/tools/default.asp">Tool Tutorials</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/atec.asp">Courses</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/peer/default.asp">Peer Support</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/mastering.asp">CD-ROM Training</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/books_kits.asp">Books & Training Kits</DIV>
		<DIV expURL="http://www.microsoft.com/workshop/c-frame.htm#/devtraining/mscert/default.asp">Certification</DIV>
	</DIV>
	<DIV ID="divMenu6" CLASS="clsMenu" ONMOUSEOVER="Menu_hover();" ONMOUSEOUT="Menu_hover();" ONCLICK="Menu_click();">
		<DIV expURL="http://www.microsoft.com/sitebuilder/default.htm">SBN Home</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/siteinfo/newtosite.asp">New to SBN?</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/whatsnew.asp">What's New on SBN</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/siteinfo/sitemap.asp">Site Map</DIV>
		<DIV expURL="http://www.microsoft.com/isapi/gosearch.asp?TARGET=/dev/web/default.asp">Site Search</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/siteinfo/glossary/default.asp">Glossary</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/write-us.asp">Write Us</DIV>
		<DIV expURL="http://www.microsoft.com/sitebuilder/siteinfo/about.asp">Using This Site</DIV>
	</DIV>
